### ISSUE TITLE
Create collection from the media upload UI

### ISSUE THREAD

**Issue by daptontdev1** [optimistdigital/nova-media-field#21]
Hi, Is there any way for creating a collection name from UI. It would be very useful I think. Thanks

**Comment by marttinnotta** [comment]
Not possible in v1. In v2 alpha it should be possible by overriding our core classes add that logic but there will be issues on the way. I think you would need to add this as separate feature as collections defined in config serve a bit different purpose.

Collection in config is meant for developer to restrict user input when uploading files, ex. when you want to allow upload file with specific conditions. This is not meant for end user to create and manage collections like grouping folders.
