### ISSUE TITLE
Is this package postgresql friendly?

### ISSUE THREAD

**Issue by LINKeRxUA** [optimistdigital/nova-media-field#22]
Hello! I have 500 on this routes:
/api/media/find?ids[]=8
/api/media/find?ids[]=7&ids[]=5&ids[]=9&ids[]=6

The exception message is : 
"SQLSTATE[42883]: Undefined function: 7 ERROR:  function field(bigint, integer, integer, integer, integer) does not exist\nLINE 1: ..._library\" where \"id\" in ($1, $2, $3, $4) order by FIELD (id,...\n                                                             ^\nHINT:  No function matches the given name and argument types. You might need to add explicit type casts. (SQL: select * from \"media_library\" where \"id\" in (7, 5, 9, 6) order by FIELD (id, 7,5,9,6))",

[Possible solution with sql CASE](https://stackoverflow.com/a/1310188/3894584)

But in most cases it's enough to sort using php functions

**Comment by LINKeRxUA** [comment]
Please, accept my pull request [#23](https://github.com/optimistdigital/nova-media-field/pull/23)

**Comment by Tarpsvo** [comment]
Hey @LINKeRxUA!

Thanks for the report and PR. :) I merged it and released it in version 1.3.10. Good luck!
