### ISSUE TITLE
File URL for S3 filesystems

### ISSUE THREAD

**Issue by jonkootje** [optimistdigital/nova-media-field#25]
Right now the URL is generated by combining the config('app.url') value with the Storage::url() value. In case a S3 or minio filesystem is used, the Storage::url() returns a full URL that should not be combined with the application URL since its a seperate domain / IP. 

I think in general you should only use Storage::url() and ignore the config('app.url') value.

**Comment by marttinnotta** [comment]
Fix has been applied for v2 alpha version so this fix will end up in v2.
