### ISSUE TITLE
Usage with page manager

### ISSUE THREAD

**Issue by JeremDigi** [optimistdigital/nova-media-field#47]
Hello,

I would like to use this package with your Page Manager.
How do you use it with? 

I get my "data" object with this as data for images : 

```
"data": {
   "title": "My beautiful title",
   "media": "3"
},
```

I use helper `nova_page_manager_get_page_by_path`

Thanks for your help!

**Comment by Tarpsvo** [comment]
You have to modify the data yourself. For example, `$data['media'] = $data['media'] ? Media::find($data['media']) : null;` etc.
