### ISSUE TITLE
How is the index display for this media field?

### ISSUE THREAD

**Issue by dkc17** [optimistdigital/nova-media-field#5]
Is there any plan to handle the index display for this media field?

Or can I have somewhere to have my own .vue overriding?

Thanks!

This is a great field!

**Comment by adin00** [comment]
Here's how I solved this:
1. Create a relationship on model (make sure the actual field name is different):
` public function logo() {
    return $this->belongsTo(\OptimistDigital\MediaField\Models\Media::class, 'logo_id');
  }`

2. on Resource fields() add
`Image::make('Logo', 'logo->thumbnailPath')->onlyOnIndex()`

and finally add hideFromIndex() on MediaField

**Comment by marttinnotta** [comment]
Index field that displays thumbnails instead list of media IDs is now added with version 2
