### ISSUE TITLE
Limiting by mime type

### ISSUE THREAD

**Issue by fecony** [optimistdigital/nova-media-field#56]
It would be good UX to show media content of specific "type" on that one page. 
So when I have to choose Image for my banner I see Media Library with `image/*` type files, and not everything I have uploaded.

### Possible implementation
```
MediaField::make(__('Banner images'), 'banner_images')
    ->multiple()
    //->type('image/*')
      ->type(['image/png', 'image/gif']),
```

I don't know if this package is still maintained but help on how to implement this would me nice  in order to prepare PR

**Comment by marttinnotta** [comment]
Have you tried using [collections](https://github.com/outl1ne/nova-media-field#Collections)?
After you have defined your collections you can call `->collection("collection-key")` on media field.
Sounds like this should do what you have described.

**Comment by fecony** [comment]
@marttinnotta Yes it was my initial idea.

But you cannot specify collection when you upload file with Media Library resource, sooo it doesn't work for me

**Comment by fecony** [comment]
Closing because the repository is dead
