### ISSUE TITLE
Nova 4 support

### ISSUE THREAD

**Issue by bracketsdigital** [optimistdigital/nova-media-field#57]
Support for this within Nova 4 would be great.

**Comment by grandcreation** [comment]
I am waiting for the good news too

**Comment by Tarpsvo** [comment]
Hi! We've decided to not migrate Nova Media Field to Nova 4. Instead, I developed a new package called [Nova Media Hub](https://github.com/outl1ne/nova-media-hub) which serves as a replacement and should be an improvement over the existing package.
