### ISSUE TITLE
Call to undefined method Illuminate\Database\Eloquent\Casts\Attribute::make()

### ISSUE THREAD

**Issue by keeliang** [optimistdigital/nova-media-field#60]
Call to undefined method Illuminate\Database\Eloquent\Casts\Attribute::make() {"exception":"[object] (Error(code: 0): Call to undefined method Illuminate\\Database\\Eloquent\\Casts\\Attribute::make()

Laravel version 8.83.25  

fixed:
Media.php
protected function data(): Attribute
    {
         return new Attribute(fn ($value) => json_decode($value, true),fn ($value) => is_string($value) ? $value : json_encode($value));
}

**Comment by KasparRosin** [comment]
Fixed in version 3.1.0
There was syntax only available for L9
