### ISSUE TITLE
Add an option to define my own MediaHandler class

### ISSUE THREAD

**Issue by milewski** [optimistdigital/nova-media-field#7]
Hi, can you add an option to give my own version of the `OptimistDigital\MediaField\Classes\MediaHandler` class file? 

I want to override the `generateImageSizes` to automatically generate the image sizes following this logic here: https://github.com/spatie/laravel-medialibrary/blob/master/src/ResponsiveImages/WidthCalculator/FileSizeOptimizedWidthCalculator.php

Having a hardcoded number for all the sizes an image should be downscaled to sometimes is not optimal for my use case, having the ability to define my own logic would be awesome.

**Comment by Tarpsvo** [comment]
Merged PR #8 and released it in version 1.1.0. Thanks a ton!
